# Generated by Django 4.2.5 on 2023-09-27 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Stock', models.CharField(max_length=20)),
                ('Open', models.DecimalField(decimal_places=2, max_digits=6)),
                ('Close', models.DecimalField(decimal_places=2, max_digits=6)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
